# Generated by Django 6.0.4 on 2026-05-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusfila',
            name='mostrar_horarios',
            field=models.BooleanField(default=True),
        ),
    ]
