# Generated by Django 6.0.4 on 2026-05-16 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('_cpf_proprietario', models.TextField(db_column='cpf_proprietario')),
                ('telefone', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('plano', models.CharField(choices=[('trial', 'Trial Gratuito'), ('ativo', 'Assinatura Ativa'), ('suspenso', 'Aguardando Pagamento'), ('cancelado', 'Cancelado')], default='trial', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('pagamento_solicitado', models.BooleanField(default=False)),
                ('data_pagamento_solicitado', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barbearia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barbearia',
                'verbose_name_plural': 'Barbearias',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.TextField(blank=True)),
                ('atendido', models.BooleanField(default=False)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='accounts.barbearia')),
            ],
            options={
                'verbose_name': 'Solicitação de Pagamento',
                'verbose_name_plural': 'Solicitações de Pagamento',
                'ordering': ['-data'],
            },
        ),
    ]
