# Generated by Django 6.0.4 on 2026-05-18 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verificacao_unicidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('qr_code', models.TextField(blank=True)),
                ('qr_code_base64', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, default=20, max_digits=8)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_mp', to='accounts.barbearia')),
            ],
            options={
                'verbose_name': 'Pagamento Mercado Pago',
                'verbose_name_plural': 'Pagamentos Mercado Pago',
                'ordering': ['-criado_em'],
            },
        ),
    ]
