# Generated by Django 6.0.4 on 2026-05-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pagamentomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='token_reset_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='token_reset_senha',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
