# Generated by Django 5.2.10 on 2026-05-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_barbearia_token_reset_expira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='plano',
            field=models.CharField(choices=[('trial', 'Período de Teste'), ('ativo', 'Assinatura Ativa'), ('suspenso', 'Aguardando Pagamento'), ('cancelado', 'Cancelado')], default='trial', max_length=20),
        ),
    ]
