# Generated by Django 5.2.10 on 2026-05-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_barbearia_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentomp',
            name='plano_escolhido',
            field=models.CharField(default='pro', max_length=10),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='plano',
            field=models.CharField(choices=[('trial', 'Período de Teste'), ('pro', 'Pro — R$14,90/mês'), ('max', 'Max — R$34,90/mês'), ('ativo', 'Ativo (legado)'), ('suspenso', 'Aguardando Pagamento'), ('cancelado', 'Cancelado')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamentomp',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=14.9, max_digits=8),
        ),
    ]
