# Generated by Django 5.2.10 on 2026-05-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_plano_escolhido'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='asaas_customer_id',
            field=models.CharField(blank=True, help_text='ID do cliente no Asaas', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='asaas_sub_id',
            field=models.CharField(blank=True, help_text='ID da assinatura recorrente no Asaas', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='proxima_cobranca',
            field=models.DateField(blank=True, help_text='Data da próxima cobrança mensal', null=True),
        ),
    ]
